// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlkiinIDiFLhFNws3nRFpQcOw2B_s-Lz8',
    appId: '1:930992715418:web:a820408b10a338f6955123',
    messagingSenderId: '930992715418',
    projectId: 'jong-ming-wedding',
    authDomain: 'jong-ming-wedding.firebaseapp.com',
    storageBucket: 'jong-ming-wedding.firebasestorage.app',
    measurementId: 'G-YBNLR63H8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApfE-I8GmhDpf_i5zd0ZVtCjWjEVgKxCM',
    appId: '1:930992715418:android:2b0d2fa70c1c25a5955123',
    messagingSenderId: '930992715418',
    projectId: 'jong-ming-wedding',
    storageBucket: 'jong-ming-wedding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQQ8n1kUkae5G7VQGbqLyOkjB1__JpRAg',
    appId: '1:930992715418:ios:e4a791f4264aa6a9955123',
    messagingSenderId: '930992715418',
    projectId: 'jong-ming-wedding',
    storageBucket: 'jong-ming-wedding.firebasestorage.app',
    iosBundleId: 'ming.jong.wedding',
  );

}